name: CI
on:
    push:
        branches:
            - master
    pull_request:
            branches:
                - master
jobs:
    build-tests-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false
            - name: Install and Build
            - run: |
                  yarn install
                  yarn build
            - run: yarn test
            - run: yarn lint
